name: Validate Configuration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate docker-compose configuration
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: |
          docker compose -f docker-compose.yml config --quiet
          echo "✓ docker-compose.yml is valid"

      - name: Validate nginx.conf syntax
        run: |
          docker run --rm -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t -c /etc/nginx/nginx.conf
          echo "✓ nginx.conf is valid"
